In [ ]:
#EDA
import pandas as pd
import statsmodels as sm
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
dataf = pd.read_csv('raw_data.csv')#, index_col = 'Date', parse_dates=True)
dataf['Date'] = pd.to_datetime(dataf['Date'], dayfirst=True)

In [ ]:
dataf

          Date  r1mw  r2mw  r3mw  r4mw  r1m  ...  r3c  r4c  r1a   r2a   r3a   r4a
0   2009-01-01    26    41    37    24  264  ...  353  305  107   422  1367   632
1   2009-01-08    28    41    31    22  263  ...  318  304  632   632   947   632
2   2009-01-15    29    36    27    22  265  ...  309  305  737   737   947  1157
3   2009-01-22    28    35    28    25  266  ...  308  309  317   737   737  1157
4   2009-01-29    26    31    25    28  267  ...  304  311  947   842  1367  1157
..         ...   ...   ...   ...   ...  ...  ...  ...  ...  ...   ...   ...   ...
307 2014-11-20    41    33    21    47  274  ...  302  310  737  1262  1682   737
308 2014-11-27    40    27    24    45  271  ...  303  307  737   842  1577   527
309 2014-12-04    38    26    28    45  269  ...  303  307  842  1052  1367   842
310 2014-12-11    32    26    32    49  272  ...  303  307  842  1052  1472   737
311 2014-12-18    32    28    32    50  272  ...  304  308  527  1367  1052   527

[312 rows x 17 columns]

In [ ]:
df_no_outlier = pd.DataFrame(dataf)

In [ ]:
products = ['r1mw',	'r2mw',	'r3mw',	'r4mw',	'r1m',	'r2m',	'r3m',	'r4m',	'r1c',	'r2c',	'r3c',	'r4c',	'r1a',	'r2a',	'r3a',	'r4a']
for i in products:
  Q1 = dataf[i].quantile(0.25)
  Q3 = dataf[i].quantile(0.75)
  IQR = Q3 - Q1
  lower_limit = Q1 - 1.5*IQR
  upper_limit = Q3 + 1.5*IQR
  df_no_outlier[i] = dataf[i][(dataf[i]>lower_limit)&(dataf[i]<upper_limit)]

In [ ]:
x = df_no_outlier.iloc[:, :].values

In [ ]:
x[0][11]

nan

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,1:])   #3 because last index is excuded
x[:,1:] = imputer.transform(x[:,1:])

In [ ]:
products = ['Date', 'r1mw',	'r2mw',	'r3mw',	'r4mw',	'r1m',	'r2m',	'r3m',	'r4m',	'r1c',	'r2c',	'r3c',	'r4c',	'r1a',	'r2a',	'r3a',	'r4a']

In [ ]:
df_clean = pd.DataFrame(x,columns=products)

In [ ]:
df_clean

          Date r1mw r2mw r3mw r4mw  r1m  ...     r3c  r4c  r1a   r2a   r3a   r4a
0   2009-01-01   26   41   37   24  264  ...  311.01  305  107   422  1367   632
1   2009-01-08   28   41   31   22  263  ...     318  304  632   632   947   632
2   2009-01-15   29   36   27   22  265  ...     309  305  737   737   947  1157
3   2009-01-22   28   35   28   25  266  ...     308  309  317   737   737  1157
4   2009-01-29   26   31   25   28  267  ...     304  311  947   842  1367  1157
..         ...  ...  ...  ...  ...  ...  ...     ...  ...  ...   ...   ...   ...
307 2014-11-20   41   33   21   47  274  ...     302  310  737  1262  1682   737
308 2014-11-27   40   27   24   45  271  ...     303  307  737   842  1577   527
309 2014-12-04   38   26   28   45  269  ...     303  307  842  1052  1367   842
310 2014-12-11   32   26   32   49  272  ...     303  307  842  1052  1472   737
311 2014-12-18   32   28   32   50  272  ...     304  308  527  1367  1052   527

[312 rows x 17 columns]

In [ ]:
products = ['Date', 'r1mw',	'r2mw',	'r3mw',	'r4mw',	'r1m',	'r1c',	'r3c',	'r1a',	'r2a',	'r3a']
for i in products:
  df_clean[i] = pd.to_numeric(df_clean[i])

In [ ]:
df_clean.dtypes

Date      int64
r1mw    float64
r2mw    float64
r3mw    float64
r4mw    float64
r1m     float64
r2m      object
r3m      object
r4m      object
r1c     float64
r2c      object
r3c     float64
r4c      object
r1a     float64
r2a     float64
r3a     float64
r4a      object
dtype: object

In [ ]:
df_clean['r1mw-1']=df_clean['r1mw'].shift(+1)
df_clean['r2mw-1']=df_clean['r2mw'].shift(+1)
df_clean['r3mw-1']=df_clean['r3mw'].shift(+1)
df_clean['r4mw-1']=df_clean['r4mw'].shift(+1)
df_clean['r1m-1']=df_clean['r1m'].shift(+1)
df_clean['r2m-1']=df_clean['r2m'].shift(+1)
df_clean['r3m-1']=df_clean['r3m'].shift(+1)
df_clean['r4m-1']=df_clean['r4m'].shift(+1)
df_clean['r1c-1']=df_clean['r1c'].shift(+1)
df_clean['r2c-1']=df_clean['r2c'].shift(+1)
df_clean['r3c-1']=df_clean['r3c'].shift(+1)
df_clean['r4c-1']=df_clean['r4c'].shift(+1)
df_clean['r1a-1']=df_clean['r1a'].shift(+1)
df_clean['r2a-1']=df_clean['r2a'].shift(+1)
df_clean['r3a-1']=df_clean['r3a'].shift(+1)
df_clean['r4a-1']=df_clean['r4a'].shift(+1)

df_clean['r1mw-2']=df_clean['r1mw'].shift(+2)
df_clean['r2mw-2']=df_clean['r2mw'].shift(+2)
df_clean['r3mw-2']=df_clean['r3mw'].shift(+2)
df_clean['r4mw-2']=df_clean['r4mw'].shift(+2)
df_clean['r1m-2']=df_clean['r1m'].shift(+2)
df_clean['r2m-2']=df_clean['r2m'].shift(+2)
df_clean['r3m-2']=df_clean['r3m'].shift(+2)
df_clean['r4m-2']=df_clean['r4m'].shift(+2)
df_clean['r1c-2']=df_clean['r1c'].shift(+2)
df_clean['r2c-2']=df_clean['r2c'].shift(+2)
df_clean['r3c-2']=df_clean['r3c'].shift(+2)
df_clean['r4c-2']=df_clean['r4c'].shift(+2)
df_clean['r1a-2']=df_clean['r1a'].shift(+2)
df_clean['r2a-2']=df_clean['r2a'].shift(+2)
df_clean['r3a-2']=df_clean['r3a'].shift(+2)
df_clean['r4a-2']=df_clean['r4a'].shift(+2)

df_clean['r1mw-3']=df_clean['r1mw'].shift(+3)
df_clean['r2mw-3']=df_clean['r2mw'].shift(+3)
df_clean['r3mw-3']=df_clean['r3mw'].shift(+3)
df_clean['r4mw-3']=df_clean['r4mw'].shift(+3)
df_clean['r1m-3']=df_clean['r1m'].shift(+3)
df_clean['r2m-3']=df_clean['r2m'].shift(+3)
df_clean['r3m-3']=df_clean['r3m'].shift(+3)
df_clean['r4m-3']=df_clean['r4m'].shift(+3)
df_clean['r1c-3']=df_clean['r1c'].shift(+3)
df_clean['r2c-3']=df_clean['r2c'].shift(+3)
df_clean['r3c-3']=df_clean['r3c'].shift(+3)
df_clean['r4c-3']=df_clean['r4c'].shift(+3)
df_clean['r1a-3']=df_clean['r1a'].shift(+3)
df_clean['r2a-3']=df_clean['r2a'].shift(+3)
df_clean['r3a-3']=df_clean['r3a'].shift(+3)
df_clean['r4a-3']=df_clean['r4a'].shift(+3)

df_clean['r1mw-4']=df_clean['r1mw'].shift(+4)
df_clean['r2mw-4']=df_clean['r2mw'].shift(+4)
df_clean['r3mw-4']=df_clean['r3mw'].shift(+4)
df_clean['r4mw-4']=df_clean['r4mw'].shift(+4)
df_clean['r1m-4']=df_clean['r1m'].shift(+4)
df_clean['r2m-4']=df_clean['r2m'].shift(+4)
df_clean['r3m-4']=df_clean['r3m'].shift(+4)
df_clean['r4m-4']=df_clean['r4m'].shift(+4)
df_clean['r1c-4']=df_clean['r1c'].shift(+4)
df_clean['r2c-4']=df_clean['r2c'].shift(+4)
df_clean['r3c-4']=df_clean['r3c'].shift(+4)
df_clean['r4c-4']=df_clean['r4c'].shift(+4)
df_clean['r1a-4']=df_clean['r1a'].shift(+4)
df_clean['r2a-4']=df_clean['r2a'].shift(+4)
df_clean['r3a-4']=df_clean['r3a'].shift(+4)
df_clean['r4a-4']=df_clean['r4a'].shift(+4)

In [ ]:
df_clean = df_clean.dropna()

In [ ]:
#"""LOOP FOR 16"""
def mape(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    return np.mean(np.abs((actual - pred) / actual)) * 100

print("The time series considered is: r1mw") ##55555555555
x1,x2,x3,y=df_clean['r1mw-1'],df_clean['r1mw-2'],df_clean['r1mw-3'],df_clean['r1mw']
x1,x2,x3,y=np.array(x1),np.array(x2),np.array(x3),np.array(y)
x1,x2,x3,y=x1.reshape(-1,1),x2.reshape(-1,1),x3.reshape(-1,1),y.reshape(-1,1)
final_x=np.concatenate((x1,x2,x3),axis=1)
print(final_x)

The time series considered is: r1mw
[[28.         29.         28.        ]
 [26.         28.         29.        ]
 [29.         26.         28.        ]
 [27.         29.         26.        ]
 [30.         27.         29.        ]
 [27.         30.         27.        ]
 [26.         27.         30.        ]
 [20.         26.         27.        ]
 [23.         20.         26.        ]
 [19.         23.         20.        ]
 [20.         19.         23.        ]
 [20.         20.         19.        ]
 [22.         20.         20.        ]
 [25.         22.         20.        ]
 [24.         25.         22.        ]
 [26.         24.         25.        ]
 [27.         26.         24.        ]
 [26.         27.         26.        ]
 [29.         26.         27.        ]
 [26.         29.         26.        ]
 [28.         26.         29.        ]
 [27.         28.         26.        ]
 [27.         27.         28.        ]
 [27.         27.         27.        ]
 [31.         27.         27.        ]
 [30.         31.         27.        ]
 [28.         30.         31.        ]
 [32.         28.         30.        ]
 [29.         32.         28.        ]
 [27.         29.         32.        ]
 [27.         27.         29.        ]
 [20.         27.         27.        ]
 [23.         20.         27.        ]
 [23.         23.         20.        ]
 [23.         23.         23.        ]
 [20.         23.         23.        ]
 [24.         20.         23.        ]
 [27.         24.         20.        ]
 [29.         27.         24.        ]
 [42.         29.         27.        ]
 [48.         42.         29.        ]
 [42.         48.         42.        ]
 [41.         42.         48.        ]
 [42.         41.         42.        ]
 [43.         42.         41.        ]
 [38.         43.         42.        ]
 [37.         38.         43.        ]
 [42.         37.         38.        ]
 [43.         42.         37.        ]
 [25.         43.         42.        ]
 [32.         25.         43.        ]
 [35.         32.         25.        ]
 [50.         35.         32.        ]
 [54.         50.         35.        ]
 [45.         54.         50.        ]
 [46.         45.         54.        ]
 [42.         46.         45.        ]
 [42.         42.         46.        ]
 [42.         42.         42.        ]
 [39.         42.         42.        ]
 [47.         39.         42.        ]
 [41.         47.         39.        ]
 [39.         41.         47.        ]
 [37.         39.         41.        ]
 [34.         37.         39.        ]
 [34.         34.         37.        ]
 [31.         34.         34.        ]
 [30.         31.         34.        ]
 [24.         30.         31.        ]
 [25.         24.         30.        ]
 [25.         25.         24.        ]
 [24.         25.         25.        ]
 [26.         24.         25.        ]
 [26.         26.         24.        ]
 [33.         26.         26.        ]
 [38.         33.         26.        ]
 [38.         38.         33.        ]
 [45.         38.         38.        ]
 [42.         45.         38.        ]
 [40.         42.         45.        ]
 [42.         40.         42.        ]
 [34.         42.         40.        ]
 [37.         34.         42.        ]
 [41.         37.         34.        ]
 [43.         41.         37.        ]
 [43.         43.         41.        ]
 [34.         43.         43.        ]
 [39.         34.         43.        ]
 [36.         39.         34.        ]
 [30.         36.         39.        ]
 [29.         30.         36.        ]
 [32.         29.         30.        ]
 [29.         32.         29.        ]
 [26.         29.         32.        ]
 [21.         26.         29.        ]
 [22.         21.         26.        ]
 [23.         22.         21.        ]
 [24.         23.         22.        ]
 [30.         24.         23.        ]
 [37.         30.         24.        ]
 [48.         37.         30.        ]
 [30.         48.         37.        ]
 [28.         30.         48.        ]
 [29.         28.         30.        ]
 [25.         29.         28.        ]
 [23.         25.         29.        ]
 [21.         23.         25.        ]
 [24.         21.         23.        ]
 [24.         24.         21.        ]
 [27.         24.         24.        ]
 [29.         27.         24.        ]
 [33.         29.         27.        ]
 [33.07395498 33.         29.        ]
 [45.         33.07395498 33.        ]
 [42.         45.         33.07395498]
 [45.         42.         45.        ]
 [42.         45.         42.        ]
 [40.         42.         45.        ]
 [41.         40.         42.        ]
 [39.         41.         40.        ]
 [42.         39.         41.        ]
 [40.         42.         39.        ]
 [42.         40.         42.        ]
 [39.         42.         40.        ]
 [36.         39.         42.        ]
 [31.         36.         39.        ]
 [29.         31.         36.        ]
 [25.         29.         31.        ]
 [24.         25.         29.        ]
 [25.         24.         25.        ]
 [18.         25.         24.        ]
 [24.         18.         25.        ]
 [24.         24.         18.        ]
 [24.         24.         24.        ]
 [28.         24.         24.        ]
 [33.         28.         24.        ]
 [36.         33.         28.        ]
 [36.         36.         33.        ]
 [34.         36.         36.        ]
 [29.         34.         36.        ]
 [35.         29.         34.        ]
 [30.         35.         29.        ]
 [31.         30.         35.        ]
 [26.         31.         30.        ]
 [32.         26.         31.        ]
 [29.         32.         26.        ]
 [28.         29.         32.        ]
 [25.         28.         29.        ]
 [26.         25.         28.        ]
 [24.         26.         25.        ]
 [24.         24.         26.        ]
 [22.         24.         24.        ]
 [17.         22.         24.        ]
 [41.         17.         22.        ]
 [38.         41.         17.        ]
 [38.         38.         41.        ]
 [43.         38.         38.        ]
 [40.         43.         38.        ]
 [39.         40.         43.        ]
 [40.         39.         40.        ]
 [34.         40.         39.        ]
 [36.         34.         40.        ]
 [36.         36.         34.        ]
 [26.         36.         36.        ]
 [26.         26.         36.        ]
 [22.         26.         26.        ]
 [24.         22.         26.        ]
 [23.         24.         22.        ]
 [26.         23.         24.        ]
 [25.         26.         23.        ]
 [49.         25.         26.        ]
 [58.         49.         25.        ]
 [56.         58.         49.        ]
 [53.         56.         58.        ]
 [45.         53.         56.        ]
 [48.         45.         53.        ]
 [46.         48.         45.        ]
 [44.         46.         48.        ]
 [43.         44.         46.        ]
 [38.         43.         44.        ]
 [40.         38.         43.        ]
 [41.         40.         38.        ]
 [40.         41.         40.        ]
 [41.         40.         41.        ]
 [41.         41.         40.        ]
 [33.         41.         41.        ]
 [30.         33.         41.        ]
 [28.         30.         33.        ]
 [29.         28.         30.        ]
 [24.         29.         28.        ]
 [21.         24.         29.        ]
 [22.         21.         24.        ]
 [23.         22.         21.        ]
 [25.         23.         22.        ]
 [27.         25.         23.        ]
 [36.         27.         25.        ]
 [31.         36.         27.        ]
 [31.         31.         36.        ]
 [32.         31.         31.        ]
 [28.         32.         31.        ]
 [33.         28.         32.        ]
 [29.         33.         28.        ]
 [30.         29.         33.        ]
 [29.         30.         29.        ]
 [34.         29.         30.        ]
 [24.         34.         29.        ]
 [28.         24.         34.        ]
 [34.         28.         24.        ]
 [31.         34.         28.        ]
 [30.         31.         34.        ]
 [35.         30.         31.        ]
 [33.         35.         30.        ]
 [29.         33.         35.        ]
 [32.         29.         33.        ]
 [28.         32.         29.        ]
 [29.         28.         32.        ]
 [38.         29.         28.        ]
 [37.         38.         29.        ]
 [40.         37.         38.        ]
 [36.         40.         37.        ]
 [36.         36.         40.        ]
 [32.         36.         36.        ]
 [34.         32.         36.        ]
 [28.         34.         32.        ]
 [23.         28.         34.        ]
 [24.         23.         28.        ]
 [24.         24.         23.        ]
 [23.         24.         24.        ]
 [25.         23.         24.        ]
 [27.         25.         23.        ]
 [28.         27.         25.        ]
 [33.         28.         27.        ]
 [35.         33.         28.        ]
 [34.         35.         33.        ]
 [32.         34.         35.        ]
 [34.         32.         34.        ]
 [32.         34.         32.        ]
 [34.         32.         34.        ]
 [32.         34.         32.        ]
 [35.         32.         34.        ]
 [38.         35.         32.        ]
 [39.         38.         35.        ]
 [31.         39.         38.        ]
 [35.         31.         39.        ]
 [39.         35.         31.        ]
 [34.         39.         35.        ]
 [32.         34.         39.        ]
 [27.         32.         34.        ]
 [33.         27.         32.        ]
 [29.         33.         27.        ]
 [28.         29.         33.        ]
 [27.         28.         29.        ]
 [27.         27.         28.        ]
 [33.         27.         27.        ]
 [46.         33.         27.        ]
 [55.         46.         33.        ]
 [53.         55.         46.        ]
 [34.         53.         55.        ]
 [30.         34.         53.        ]
 [29.         30.         34.        ]
 [27.         29.         30.        ]
 [24.         27.         29.        ]
 [23.         24.         27.        ]
 [26.         23.         24.        ]
 [28.         26.         23.        ]
 [30.         28.         26.        ]
 [32.         30.         28.        ]
 [43.         32.         30.        ]
 [44.         43.         32.        ]
 [43.         44.         43.        ]
 [42.         43.         44.        ]
 [44.         42.         43.        ]
 [46.         44.         42.        ]
 [45.         46.         44.        ]
 [45.         45.         46.        ]
 [43.         45.         45.        ]
 [42.         43.         45.        ]
 [42.         42.         43.        ]
 [38.         42.         42.        ]
 [42.         38.         42.        ]
 [38.         42.         38.        ]
 [38.         38.         42.        ]
 [38.         38.         38.        ]
 [32.         38.         38.        ]
 [29.         32.         38.        ]
 [25.         29.         32.        ]
 [26.         25.         29.        ]
 [28.         26.         25.        ]
 [28.         28.         26.        ]
 [28.         28.         28.        ]
 [32.         28.         28.        ]
 [40.         32.         28.        ]
 [41.         40.         32.        ]
 [42.         41.         40.        ]
 [37.         42.         41.        ]
 [34.         37.         42.        ]
 [38.         34.         37.        ]
 [39.         38.         34.        ]
 [35.         39.         38.        ]
 [41.         35.         39.        ]
 [41.         41.         35.        ]
 [42.         41.         41.        ]
 [45.         42.         41.        ]
 [45.         45.         42.        ]
 [41.         45.         45.        ]
 [40.         41.         45.        ]
 [38.         40.         41.        ]
 [32.         38.         40.        ]]

In [ ]:
final_x[-1:].shape

(1, 3)

In [ ]:


#    """LINEAR REGRESSION"""

from sklearn.linear_model import LinearRegression
lin_model=LinearRegression()

lin_model.fit(final_x,y)

test_predictions = []

first_eval_batch = final_x[-1:]
current_batch = first_eval_batch #.reshape((1, 3, 1))
print(current_batch)
current_batch.reshape(-1, 1)
for j in range(52):
  #print(j)
# get the prediction value for the first batch
  current_pred = lin_model.predict(current_batch)
  #print(current_pred)
# append the prediction into the array
  test_predictions.append(current_pred[0][0]) 
  #print(test_predictions)
# use the prediction to update the batch and remove the first value
  current_batch = np.array([np.append(current_batch[0,1:3],current_pred)])
  #print(current_batch)
  current_batch.reshape(-1,1)

pred2 = np.roll(test_predictions,-1)
#####################################################

[[32. 38. 40.]]

LINEAR REG LOOP

In [ ]:
products = ['r1mw',	'r2mw',	'r3mw',	'r4mw',	'r1m',	'r1c',	'r3c',	'r1a',	'r2a',	'r3a']
output = []
def mape(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    return np.mean(np.abs((actual - pred) / actual)) * 100

#    """LINEAR REGRESSION"""
for i in products:
  
  print("The time series considered is: ",i) 
  x1,x2,x3,y=df_clean[i+'-1'],df_clean[i+'-2'],df_clean[i+'-3'],df_clean[i]
  x1,x2,x3,y=np.array(x1),np.array(x2),np.array(x3),np.array(y)
  x1,x2,x3,y=x1.reshape(-1,1),x2.reshape(-1,1),x3.reshape(-1,1),y.reshape(-1,1)
  final_x=np.concatenate((x1,x2,x3),axis=1)
  #print(final_x)

  from sklearn.linear_model import LinearRegression
  lin_model=LinearRegression()

  lin_model.fit(final_x,y)

  test_predictions = []

  first_eval_batch = final_x[-1:]
  current_batch = first_eval_batch #.reshape((1, 3, 1))
  print(current_batch)
  current_batch.reshape(-1, 1)
  for j in range(52):
	  #print(j)
	# get the prediction value for the first batch
	  current_pred = lin_model.predict(current_batch)
	  #print(current_pred)
	# append the prediction into the array
	  test_predictions.append(current_pred[0][0]) 
	  #print(test_predictions)
	# use the prediction to update the batch and remove the first value
	  current_batch = np.array([np.append(current_batch[0,1:3],current_pred)])
	  #print(current_batch)
	  current_batch.reshape(-1,1)

  pred2 = np.roll(test_predictions,-1)
  output.append(pred2)
	#####################################################

The time series considered is:  r1mw
[[32. 38. 40.]]
The time series considered is:  r2mw
[[26. 26. 27.]]
The time series considered is:  r3mw
[[32. 28. 24.]]
The time series considered is:  r4mw
[[49. 45. 45.]]
The time series considered is:  r1m
[[272. 269. 271.]]
The time series considered is:  r1c
[[302. 307. 310.]]
The time series considered is:  r3c
[[303. 303. 303.]]
The time series considered is:  r1a
[[842. 842. 737.]]
The time series considered is:  r2a
[[1052. 1052.  842.]]
The time series considered is:  r3a
[[1472. 1367. 1577.]]

In [ ]:
print(output)

In [ ]:
outputo = pd.DataFrame(output)
outputo.to_csv('LinReg_Output.csv')

RANDOM FOREST

In [ ]:
products = ['r4m']
output1 = []
def mape(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    return np.mean(np.abs((actual - pred) / actual)) * 100

#    """RANDOM FOREST REGRESSION"""
for i in products:
  
  print("The time series considered is: ",i) 
  x1,x2,x3,y=df_clean[i+'-1'],df_clean[i+'-2'],df_clean[i+'-3'],df_clean[i]
  x1,x2,x3,y=np.array(x1),np.array(x2),np.array(x3),np.array(y)
  x1,x2,x3,y=x1.reshape(-1,1),x2.reshape(-1,1),x3.reshape(-1,1),y.reshape(-1,1)
  final_x=np.concatenate((x1,x2,x3),axis=1)
  #print(final_x)

  from sklearn.ensemble import RandomForestRegressor
  lin_model=RandomForestRegressor()

  lin_model.fit(final_x,y)

  test_predictions = []

  first_eval_batch = final_x[-1:]
  current_batch = first_eval_batch #.reshape((1, 3, 1))
  print(current_batch)
  current_batch.reshape(-1, 1)
  for j in range(52):
	  #print(j)
	# get the prediction value for the first batch
	  current_pred = lin_model.predict(current_batch)
	  #print(current_pred)
	# append the prediction into the array
	  test_predictions.append(current_pred[0]) 
	  #print(test_predictions)
	# use the prediction to update the batch and remove the first value
	  current_batch = np.array([np.append(current_batch[0,1:3],current_pred)])
	  #print(current_batch)
	  current_batch.reshape(-1,1)

  pred2 = np.roll(test_predictions,-1)
  output1.append(pred2)
	#####################################################

The time series considered is:  r4m
[[264.0 267.0 267.0]]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().

In [ ]:
outputo1 = pd.DataFrame(output1)
outputo1.to_csv('Random_Forest_Output.csv')

SUPPORT VECTOR REGRESSION

In [ ]:
products = ['r2m','r3m','r2c','r4c','r4a']
output2 = []
def mape(actual, pred): 
    actual, pred = np.array(actual), np.array(pred)
    return np.mean(np.abs((actual - pred) / actual)) * 100

#    """SUPPORT VECTOR REGRESSION"""
for i in products:
  
  print("The time series considered is: ",i) 
  x1,x2,x3,y=df_clean[i+'-1'],df_clean[i+'-2'],df_clean[i+'-3'],df_clean[i]
  x1,x2,x3,y=np.array(x1),np.array(x2),np.array(x3),np.array(y)
  x1,x2,x3,y=x1.reshape(-1,1),x2.reshape(-1,1),x3.reshape(-1,1),y.reshape(-1,1)
  final_x=np.concatenate((x1,x2,x3),axis=1)
  #print(final_x)

  from sklearn.preprocessing import StandardScaler
  scx = StandardScaler()
  scy = StandardScaler()
  x = scx.fit_transform(final_x) #fit will calculate the mean and sd and transform applies the formula
  y = scy.fit_transform(y)
  from sklearn.svm import SVR
  lin_model=SVR(kernel = 'rbf')

  lin_model.fit(final_x,y)

  test_predictions = []

  first_eval_batch = final_x[-1:]
  current_batch = first_eval_batch #.reshape((1, 3, 1))
  print(current_batch)
  current_batch.reshape(-1, 1)
  for j in range(52):
	  #print(j)
	# get the prediction value for the first batch
    current_pred = lin_model.predict(current_batch)
    current_pred = scy.inverse_transform(current_pred)
	  #print(current_pred)
	# append the prediction into the array
    test_predictions.append(current_pred[0]) 
	  #print(test_predictions)
	# use the prediction to update the batch and remove the first value
    current_batch = np.array([np.append(current_batch[0,1:3],current_pred)])
	  #print(current_batch)
    current_batch.reshape(-1,1)

  pred2 = np.roll(test_predictions,-1)
  output2.append(pred2)
	#####################################################

The time series considered is:  r2m
[[273.0 270.0 272.0]]
The time series considered is:  r3m
[[266.0 265.0 268.0]]
The time series considered is:  r2c
[[305.0 304.0 304.0]]
The time series considered is:  r4c
[[307.0 307.0 307.0]]
The time series considered is:  r4a
[[737.0 842.0 527.0]]

/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [ ]:
outputo2 = pd.DataFrame(output2)
outputo2.to_csv('SVR_Output.csv')